# .github/workflows/deploy.yml
name: Deploy Website via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Sync to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false
          log-level: standard
          exclude: |
            **/.git**
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            **/*.psd
            **/*.ai
            **/*.fig
            **/*.sketch
            **/*.raw
